#ifndef QCANONCAMERA_GLOBAL_H
#define QCANONCAMERA_GLOBAL_H

#include <QtCore/qglobal.h>


#ifdef QCANONCAMERA_LIB
# define QCANONCAMERA_EXPORT Q_DECL_EXPORT
#else
# define QCANONCAMERA_EXPORT Q_DECL_IMPORT
#endif

#endif // QCANONCAMERA_GLOBAL_H
